spring:
  data:
    mongodb:
      uri: mongodb://host:27017/ratingservices
  application:
    name: RATING-SERVICE
server:
  port: 8083


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


okta:
  oauth2:
    issuer: https://dev-74527726.okta.com/oauth2/default
    audience: api://default
